### ISSUE TITLE
No se validan tipos al ingresar datos

### ISSUE THREAD

**Issue by SantiagoSotoC-zz** [Fisica-Python/caida-libre#5]
No se valida el tipo de datos al ser ingresados el sistema permite ingresar un String cuando se solicita un numero esto genera una excepción que no es procesada

**Comment by fisicamaldonado** [comment]
Ok Santi, esto pasó antes de los pull request y los cambios que introdujimos? Gracias por la ayuda!

**Comment by SantiagoSotoC-zz** [comment]
Si esto estaba antes es la forma en que se piden los datos es fácil de arreglar en un rato le meto un podo de mano y lo arreglo

**Comment by fisicamaldonado** [comment]
Muchas gracias Santi!
